### PR TITLE
fix pip install error

### PR DESCRIPTION
**Pull request by hudeng-go**

### CODE REVIEW

**Comment by UTsweetyfish** [comment]
修了什么 error 呢🤔

**Comment by hudeng-go** [comment]
> 修了什么 error 呢thinking

pip3 install 报错。

**Comment by UTsweetyfish** [comment]
> > 修了什么 error 呢thinking
> 
> pip3 install 报错。

具体呢。。？

**Review by UTsweetyfish — APPROVED** [review]

**Comment by hudeng-go** [comment]
复现错误：
$ pip3 install doxyqml

ERROR: Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'doxyqml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 346, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    self._result = resolver.resolve(
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 82, in from_requirement
    if not cands:
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 99, in __bool__
    return any(self)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 220, in iter_index_candidates
    result = self._finder.find_best_candidate(
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 882, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 825, in find_all_candidates
    package_links = self.process_project_url(
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 789, in process_project_url
    html_page = self._link_collector.fetch_page(project_url)
  File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 618, in fetch_page
    return _get_html_page(location, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 430, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 127, in _get_html_response
    resp = session.get(
  File "/usr/share/python-wheels/requests-2.25.1-py2.py3-none-any.whl/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/_internal/network/session.py", line 428, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.25.1-py2.py3-none-any.whl/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.25.1-py2.py3-none-any.whl/requests/sessions.py", line 697, in send
    r.content
  File "/usr/share/python-wheels/requests-2.25.1-py2.py3-none-any.whl/requests/models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/share/python-wheels/requests-2.25.1-py2.py3-none-any.whl/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/share/python-wheels/urllib3-1.26.5-py2.py3-none-any.whl/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.26.5-py2.py3-none-any.whl/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/share/python-wheels/CacheControl-0.12.10-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 96, in read
    self._close()
  File "/usr/share/python-wheels/CacheControl-0.12.10-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 76, in _close
    self.__callback(result)
  File "/usr/share/python-wheels/CacheControl-0.12.10-py2.py3-none-any.whl/cachecontrol/controller.py", line 329, in cache_response
    self.cache.set(
TypeError: SafeFileCache.set() got an unexpected keyword argument 'expires'

**Comment by hudeng-go** [comment]
> 复现错误： $ pip3 install doxyqml
> 
> ERROR: Exception: Traceback (most recent call last): File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 171, in _merge_into_criterion crit = self.state.criteria[name] KeyError: 'doxyqml'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main status = self.run(options, args) File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper return func(self, options, args) File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 346, in run requirement_set = resolver.resolve( File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve self._result = resolver.resolve( File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 453, in resolve state = resolution.resolve(requirements, max_rounds=max_rounds) File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 318, in resolve name, crit = self._merge_into_criterion(r, parent=None) File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 173, in _merge_into_criterion crit = Criterion.from_requirement(self._p, requirement, parent) File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 82, in from_requirement if not cands: File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/structs.py", line 124, in **bool** return bool(self._sequence) File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 99, in **bool** return any(self) File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 220, in iter_index_candidates result = self._finder.find_best_candidate( File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 882, in find_best_candidate candidates = self.find_all_candidates(project_name) File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 825, in find_all_candidates package_links = self.process_project_url( File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 789, in process_project_url html_page = self._link_collector.fetch_page(project_url) File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 618, in fetch_page return _get_html_page(location, session=self.session) File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 430, in _get_html_page resp = _get_html_response(url, session=session) File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 127, in _get_html_response resp = session.get( File "/usr/share/python-wheels/requests-2.25.1-py2.py3-none-any.whl/requests/sessions.py", line 555, in get return self.request('GET', url, **kwargs) File "/usr/lib/python3/dist-packages/pip/_internal/network/session.py", line 428, in request return super(PipSession, self).request(method, url, *args, **kwargs) File "/usr/share/python-wheels/requests-2.25.1-py2.py3-none-any.whl/requests/sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "/usr/share/python-wheels/requests-2.25.1-py2.py3-none-any.whl/requests/sessions.py", line 697, in send r.content File "/usr/share/python-wheels/requests-2.25.1-py2.py3-none-any.whl/requests/models.py", line 831, in content self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b'' File "/usr/share/python-wheels/requests-2.25.1-py2.py3-none-any.whl/requests/models.py", line 753, in generate for chunk in self.raw.stream(chunk_size, decode_content=True): File "/usr/share/python-wheels/urllib3-1.26.5-py2.py3-none-any.whl/urllib3/response.py", line 576, in stream data = self.read(amt=amt, decode_content=decode_content) File "/usr/share/python-wheels/urllib3-1.26.5-py2.py3-none-any.whl/urllib3/response.py", line 519, in read data = self._fp.read(amt) if not fp_closed else b"" File "/usr/share/python-wheels/CacheControl-0.12.10-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 96, in read self._close() File "/usr/share/python-wheels/CacheControl-0.12.10-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 76, in _close self.__callback(result) File "/usr/share/python-wheels/CacheControl-0.12.10-py2.py3-none-any.whl/cachecontrol/controller.py", line 329, in cache_response self.cache.set( TypeError: SafeFileCache.set() got an unexpected keyword argument 'expires'

之前修复dh-python的错误就是为了解决这个错误的，修复链贼长呀。

**Pull request merged**
